In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_wine

from sklearn.metrics import r2_score , mean_absolute_error , mean_squared_error

In [3]:
veri = load_wine()

df= pd.DataFrame(data = veri.data , columns=veri.feature_names)

df["proline"]= veri.target

In [4]:
df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines     proline  
count       178.000000  178.000000                    178.000000  178.000000  
mean          5.058090    0.957449                      2.611685    0.938202  
std           2.318286    0.228572                      0.709990    0.775035  
min           1.280000    0.480000                      1.270000    0.000000  
25%           3.220000    0.782500                      1.937500    0.000000  
50%           4.690000    0.965000                      2.780000    1.000000  
75%           6.200000    1.120000                      3.170000    2.000000  
max          13.000000    1.710000                      4.000000    2.000000

In [5]:
x= df.drop("proline" , axis=1)
y= df["proline"]

# Polinom Dönüşümü

In [6]:
from sklearn.preprocessing import PolynomialFeatures

poly_conv = PolynomialFeatures(degree=2 , include_bias=False)

poly_feat= poly_conv.fit_transform(x)

# TRAİN TEST SPLİT

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train , X_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=9)

# STANDART SCALER

ortalama =  0 
standart sapma = 1 

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()

In [11]:
X_train

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
142    13.52        3.17  2.72               23.5       97.0           1.55   
55     13.56        1.73  2.46               20.5      116.0           2.96   
93     12.29        2.83  2.22               18.0       88.0           2.45   
94     11.62        1.99  2.28               18.0       98.0           3.02   
145    13.16        3.57  2.15               21.0      102.0           1.50   
..       ...         ...   ...                ...        ...            ...   
150    13.50        3.12  2.62               24.0      123.0           1.40   
56     14.22        1.70  2.30               16.3      118.0           3.20   
177    14.13        4.10  2.74               24.5       96.0           2.05   
92     12.69        1.53  2.26               20.7       80.0           1.38   
126    12.43        1.53  2.29               21.5       86.0           2.74   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
142        0.52                  0.50             0.55             4.35  0.89   
55         2.78                  0.20             2.45             6.25  0.98   
93         2.25                  0.25             1.99             2.15  1.15   
94         2.26                  0.17             1.35             3.25  1.16   
145        0.55                  0.43             1.30             4.00  0.60   
..          ...                   ...              ...              ...   ...   
150        1.57                  0.22             1.25             8.60  0.59   
56         3.00                  0.26             2.03             6.38  0.94   
177        0.76                  0.56             1.35             9.20  0.61   
92         1.46                  0.58             1.62             3.05  0.96   
126        3.15                  0.39             1.77             3.94  0.69   

     od280/od315_of_diluted_wines  
142                          2.06  
55                           3.03  
93                           3.30  
94                           2.96  
145                          1.68  
..                            ...  
150                          1.30  
56                           3.31  
177                          1.60  
92                           2.06  
126                          2.84  

[142 rows x 12 columns]

In [12]:
scaler.fit(X_train)

StandardScaler()

In [13]:
X_train = scaler.transform(X_train)

In [14]:
X_test = scaler.transform(X_test)


# RİGDE REGRESYON
bias = veri kaybını önlemek

varyans = verideki dağınıklılığı önlemek

yüksek varyans = overfitting

yüksek bias = underfitting



In [15]:
from sklearn.linear_model import Ridge


In [16]:
ridge_model = Ridge(alpha =1)

In [17]:
ridge_model.fit(X_train , y_train)

Ridge(alpha=1)

In [18]:
ridge_pred = ridge_model.predict(X_test)

In [19]:
print("R^2 : " , round(r2_score(y_test , ridge_pred),2))
print("MAE : " , round(mean_absolute_error(y_test , ridge_pred),2))
print("RMSE : " , round(mean_squared_error(y_test , ridge_pred),2))

R^2 :  0.85
MAE :  0.26
RMSE :  0.1


# Alpha değeri için

In [20]:
from sklearn.linear_model import RidgeCV

In [21]:
ridge_cv = RidgeCV(alphas=[0.1, 1, 10, 100, 1000], store_cv_values=True)

In [22]:
ridge_cv.fit(X_train , y_train)

C:\Users\hdgn5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_ridge.py:2385: FutureWarning: 'store_cv_values' is deprecated in version 1.5 and will be removed in 1.7. Use 'store_cv_results' instead.
  warnings.warn(


RidgeCV(alphas=[0.1, 1, 10, 100, 1000], store_cv_values=True)

In [23]:
ridge_cv.alpha_ # en iyi alpha değeri 1 

np.float64(10.0)

In [52]:
ridge_model1 = Ridge(alpha =10)

In [53]:
ridge_model1.fit(X_train , y_train)

Ridge(alpha=10)

In [54]:
ridge_pred1 = ridge_model1.predict(X_test)

In [56]:
print("R^2 : " , round(r2_score(y_test , ridge_pred1),2))
print("MAE : " , round(mean_absolute_error(y_test , ridge_pred1),2))
print("RMSE : " , round(mean_squared_error(y_test , ridge_pred1),2))

R^2 :  0.85
MAE :  0.25
RMSE :  0.1


In [28]:
df.head(7)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   
5    14.20        1.76  2.45               15.2      112.0           3.27   
6    14.39        1.87  2.45               14.6       96.0           2.50   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   
5        3.39                  0.34             1.97             6.75  1.05   
6        2.52                  0.30             1.98             5.25  1.02   

   od280/od315_of_diluted_wines  proline  
0                          3.92        0  
1                          3.40        0  
2                          3.17        0  
3                          3.45        0  
4                          2.93        0  
5                          2.85        0  
6                          3.58        0

In [29]:
alkol = [[14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92]]

In [30]:
ridge_cv.coef_


array([-0.16865577,  0.03027793, -0.08226037,  0.19753932, -0.0314238 ,
        0.02379021, -0.26903816, -0.01546665, -0.03430597,  0.13545567,
       -0.08472624, -0.20785489])

In [31]:
ridge_model.predict(alkol)


array([-3.55710484])

# LASSO

In [32]:
# Gerekli kütüphaneyi içe aktarıyoruz
from sklearn.linear_model import LassoCV
# LassoCV modelini oluşturuyoruz
lasso_cv = LassoCV(
    eps=0.1,        # Minimum ve maksimum alpha değerleri arasındaki oran (eps * alpha_max = min_alpha)
    n_alphas=100,   # Logaritmik olarak seçilecek alpha (ceza parametresi) sayısı
    cv=5            # 5 katlı çapraz doğrulama (veriyi 5 parçaya bölerek en iyi alpha'yı seçer)
)


In [33]:
lasso_cv.fit(X_train , y_train)

LassoCV(cv=5, eps=0.1)

In [34]:
lasso_cv.alpha_

np.float64(0.06326486349896114)

In [35]:
lasso_cv.coef_

# bazıları 0 olacak.
# lasso diyor ki bunlar benim işime yaramaz 0 yaptım

array([-0.07594918,  0.        , -0.        ,  0.12241041, -0.        ,
       -0.        , -0.29061274,  0.        , -0.        ,  0.        ,
       -0.09146144, -0.22486836])

In [36]:
lasso_pred = lasso_cv.predict(X_test)

In [37]:
print("R^2 : " , round(r2_score(y_test , lasso_pred),2))
print("MAE : " , round(mean_absolute_error(y_test , lasso_pred),2))
print("RMSE : " , round(mean_squared_error(y_test , lasso_pred),2))

R^2 :  0.82
MAE :  0.28
RMSE :  0.11


In [38]:



alkol=[[13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40	]]
lasso_cv.predict(alkol)

array([-0.3082953])

In [39]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92        0  
1                          3.40        0  
2                          3.17        0  
3                          3.45        0  
4                          2.93        0

# ELASTİCNET

In [40]:
from sklearn.linear_model import ElasticNetCV

In [41]:
elastic_model = ElasticNetCV(l1_ratio= (0.01 , 0.1, 0.2 , 0.3,0.4 ,0.5 , 0.6 , 0.7 , 0.8 , 0.9 , 0.95 , 0.99 , 1) , tol=0.01)

In [42]:
elastic_model.fit(X_train , y_train)

ElasticNetCV(l1_ratio=(0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95,
                       0.99, 1),
             tol=0.01)

In [43]:
elastic_model.l1_ratio_


np.float64(0.1)

In [44]:
elastic_model.coef_
# Coef lerin hiç biri 0 değil. O yüzden ridge regresyon seçilmiştir.

array([-0.17985159,  0.02606139, -0.08662758,  0.20810298, -0.03029998,
        0.06822603, -0.32530565, -0.02417751, -0.02760801,  0.14875221,
       -0.0766407 , -0.20950041])

In [45]:
elastic_pred = elastic_model.predict(X_test)

In [46]:
print("R^2 : " , round(r2_score(y_test , elastic_pred),2))
print("MAE : " , round(mean_absolute_error(y_test , elastic_pred),2))
print("RMSE : " , round(mean_squared_error(y_test , elastic_pred),2))

R^2 :  0.85
MAE :  0.25
RMSE :  0.1
